### ISSUE TITLE
License

### ISSUE THREAD

**Issue by diegovisentin** [giovibal/vertx-mqtt-broker#7]
Hi,
what is the license model of this code? 
(I would be very happy to read it's Apache License v2 :->)

**Comment by maumock** [comment]
+1 on the license

**Comment by adpande** [comment]
+1 .. Need to know the licence :)

**Comment by jchaganti** [comment]
+1 yes, would like to know the license model.

**Comment by giovibal** [comment]
Apache 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
